version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:12
commands:
  restore_modules:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "./client/package-lock.json" }}
  save_modules:
    steps:
      - save_cache:
          key: dependency-cache-{{ checksum "./client/package-lock.json" }}
          paths:
            - ./node_modules

jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: install dependencies
          working_directory: client
          command: npm install
      - save_modules

      - run:
          name: unit test
          working_directory: client
          command: npm test

      - run:
          name: execute eslint
          working_directory: client
          command: npm run lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

