version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:12
    working_directory: ~/calendar_app
  rails:
    docker:
      - image: circleci/ruby:2.6.2-node
        environment:
          RAILS_ENV: test
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLER_VERSION: 2.1.4
      - image: circleci/mysql:5.7.31-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    working_directory: ~/calendar_app

commands:
  restore_modules_client:
    steps:
      - restore_cache:
          key: v4-calendar_app-{{ .Environment.CIRCLE_SHA2 }}
      - restore_cache:
          keys: 
            - v3-dependencies-{{ checksum "client/package-lock.json" }}
            - v3-dependencies
  install_bundler:
    steps:
      - run: gem install bundler -v 2.1.4
  restore_modules_server:
    steps:
      - restore_cache:
          key: v1-calendar_app-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys: 
            - v2-dependencies-{{ checksum "Gemfile.lock" }}
            - v2-dependencies

jobs:
  fetch_source_code_client:
    executor: node
    steps:
      - checkout
      - save_cache:
          key: v4-calendar_app-{{ .Environment.CIRCLE_SHA2 }}
          paths:
            - ~/calendar_app
  npm_dependencies:
    executor: node
    steps:
      - restore_modules_client
      - run:
          name: Npm Install Dependencies
          command: npm install
      - save_cache:
          key: v3-dependencies-{{ checksum "client/package-lock.json" }}
          paths:
            - client/node_modules
  jest:
    executor: node
    steps:
      - restore_modules_client
      - run:
          name: install dependencies
          working_directory: client
          command: npm install
      - run:
          name: unit test
          working_directory: client
          command: npm test
  eslint:
    executor: node
    steps:
      - restore_modules_client
      - run:
          name: install dependencies
          working_directory: client
          command: npm install
      - run:
          name: execute eslint
          working_directory: client
          command: npm run lint

  fetch_source_code:
    executor:
      name: rails
    steps:
      - checkout
      - save_cache:
          key: v1-calendar_app-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/calendar_app
  bundle_dependencies:
    executor:
      name: rails
    steps:
      - restore_modules_server
      - install_bundler
      - run:
          name: Bundle Install Dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  rspec:
    executor:
      name: rails
    steps:
      - restore_modules_server
      - run:
          name: Watting stand up database
          command: |
            dockerize -wait \
            tcp://127.0.0.1:3306 -timeout 120s
      # Database setup
      - run: mv ./config/database.yml.ci ./config/database.yml
      - install_bundler
      - run:
          name: Testing DB migration and seed
          command: |
            bundle exec rails db:create db:migrate db:seed db:drop
      - run:
          name: Run rspec
          command: |
            mkdir /tmp/test-results
            mkdir -p ~/rspec
            bundle exec rails db:create db:migrate
            TEST_FILES="$(circleci tests glob \"spec/**/*_spec.rb\" | circleci tests split --split-by=timings)"
            bundle exec rspec --require rails_helper \
                              --color \
                              --format progress \
                              --out ~/rspec/rspec.xml
      # collect reports
      - store_test_results:
          path: ~/rspec
      - store_artifacts:
          path: ~/tmp/test-results
          destination: test-results
  rubocop:
    executor:
      name: rails
    steps:
      - restore_modules_server
      - install_bundler
      - run:
          name: Execute rubocop
          command: bundle exec rubocop

workflows:
  version: 2
  build_and_test_client:
    jobs:
      - fetch_source_code_client
      - npm_dependencies:
          requires:
            - fetch_source_code_client
      - jest:
          requires:
            - npm_dependencies
      - eslint:
          requires:
            - npm_dependencies
  build_and_test_server:
    jobs:
      - fetch_source_code
      - bundle_dependencies:
          requires:
            - fetch_source_code
      - rspec:
          requires:
            - bundle_dependencies
      - rubocop:
          requires:
            - bundle_dependencies
